### ISSUE TITLE
Welcome příkaz/oznámení

### ISSUE THREAD

**Issue by MrWakeCZ** [cybooo/corgi#34]
Každý server si bude moct nastavit vlastní "welcome" zprávu, která se odešle uživateli při připojení.

**Comment by MrFriggo** [comment]
Dal bych možnost že by se to zobrazovalo i v embedu. Když bude psát tu zprávu tak na konci by mohl dát {embed}

Př. .setwelcome Uživatel {user} se připojil{embed}

**Comment by MrWakeCZ** [comment]
@MrFriggo Spíš při vytváření volitelný zda Embed nebo text. 😄

**Comment by MrFriggo** [comment]
A nebo tak no :D
